name: DupeDetect
version: '2.0'
main: dev.nedhuman.dupedetect.DupeDetect
api-version: '1.20'
author: NedHuman
description: Minecraft plugin to aid in detecting duping
permissions:
  dupedetect.bypass:
    description: Bypass the detection of duping
  dupedetect.notify:
    description: Be notified about potential dupers
  dupedetect.getcopy:
    description: Receive a copy of a duped item
commands:
  dupedetect:
    description: Access the DupeDetect menu
    permission: dupedetect.menu